version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
